MQTT_BROKER = "550400ab5c0a4d15a091aa8699ccccf9.s1.eu.hivemq.cloud"
MQTT_PORT = 8883
MQTT_TOPIC = "picow/temperature"
MQTT_CLIENT_ID = "streamlit_subscriber"
MQTT_USERNAME = "hoshang"
MQTT_PASSWORD = "Micropython1"
